INSERT INTO "isad_reference" VALUES  (1,9,'','',1),
 (2,9,'','',2),
 (3,9,'','',3),
 (4,9,'http://hissa.nist.gov/HHRFdata/Artifacts/ITLdoc/235/chapter2.htm','Structured Testing: A Testing Methodology Using the Cyclomatic Complexity Metric',NULL),
 (6,2,'','',3),
 (8,2,'http://en.wikipedia.org/wiki/COCOMO','COCOMO',NULL),
 (9,2,'http://en.wikipedia.org/wiki/Halstead_complexity_measures','Halstead complexity measures',NULL),
 (10,2,'http://www.ifi.uzh.ch/req/courses/seminar_ws02/reports/Seminar_4.pdf','COCOMO (Constructive Cost Model), Seminar on Software Cost Estimation WS 2002 / 2003,    presented by Nancy Merlo – Schett',NULL),
 (12,1,'http://nptel.iitm.ac.in/courses/Webcourse-contents/IISc-BANG/System%20Analysis%20and%20Design/New_index1.html','Lecture on "System Analysis and Design", NPTEL',NULL),
 (13,1,'','',4),
 (14,1,'','',3),
 (15,1,'http://www.processimpact.com/articles/telepathy.html','When Telepathy Won’t Do: Requirements Engineering Key Practices',NULL),
 (16,1,'http://www.outsource2india.com/software/RequirementAnalysis.asp','Requirements Analysis: Process of requirements gathering and requirement definition',NULL),
 (17,3,'','',5),
 (18,3,'','',6),
 (19,3,'http://www.uml-diagrams.org/use-case-diagrams.html','Use Case Diagrams',NULL),
 (20,3,'http://en.wikipedia.org/wiki/Use_case_diagram','Use case diagram -- Wikipedia',NULL),
 (21,3,'http://www.omg.org/spec/UML/2.1.2/Superstructure/PDF','Unified Modeling Language, Superstructure, V2.1.2',NULL),
 (22,2,'http://www.virtualmachinery.com/sidebar2.htm','The Halstead metrics',NULL),
 (23,4,'http://www.inf.unibz.it/~franconi/teaching/2000/ct481/er-modelling/','Entity-relationship modelling',NULL),
 (24,4,'','',7),
 (25,4,'http://db.grussell.org/section005.html','Entity Relationship Modelling - 2',NULL),
 (26,5,'http://www.scribd.com/doc/44970803/Domain-Analysis','Domain Analysis',NULL),
 (27,5,'http://www.sa-depot.com/?p=336','Domain Analysis Using Textual Analysis Approach ',NULL),
 (28,5,'http://en.wikipedia.org/wiki/Domain_model','Domain model',NULL),
 (29,5,'','',8),
 (30,5,'','',3),
 (31,5,'http://www.ecst.csuchico.edu/~broggio/8.DomainModeling(B027).ppt','Business Modeling – The Domain Model',NULL),
 (32,6,'http://www.agilemodeling.com/artifacts/stateMachineDiagram.htm','UML 2 State Machine Diagrams',NULL),
 (33,6,'http://www.omg.org/news/meetings/workshops/RT_2002_Workshop_Presentations/02-1_Douglass_Modeling_Behavior_with_UML_Interactions_and_Statecharts.pdf','Modeling Behavior with UML Interactions and Statecharts',NULL),
 (34,6,'http://www.agilemodeling.com/style/stateChartDiagram.htm','UML 2 State Machine Diagramming Guidelines',NULL),
 (35,6,'http://santos.cis.ksu.edu/771-Distribution/Reading/uml-section3.73-94.pdf','Statechart Diagram',NULL),
 (36,6,'http://plantuml.sourceforge.net/index.html','PlantUML (Open-Source tool in Java to draw UML Diagram)',NULL),
 (37,6,'http://plantuml.sourceforge.net/state.html','PlantUML : State Diagram',NULL),
 (38,6,'http://en.wikipedia.org/wiki/Activity_diagram','Activity Diagram',NULL),
 (39,6,'http://www.tutorialspoint.com/uml/uml_activity_diagram.htm','UML Activity Diagram',NULL),
 (40,6,'http://www.agilemodeling.com/artifacts/activityDiagram.htm','UML 2 Activity Diagrams',NULL),
 (41,6,'http://www.uml-diagrams.org/activity-diagrams.html','Activity Diagrams',NULL),
 (42,1,'http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=720574&userType=inst','IEEE Recommended Practice for Software Requirements Specifications',NULL),
 (43,10,'','',3),
 (44,10,'http://en.wikipedia.org/wiki/IEEE_829','Standards for software test documentation',1),
 (45,10,'http://www.junit.org/','JUnit frameworks',NULL),
 (46,10,'http://seleniumhq.org/','Selenium frameworks',NULL),
 (47,10,'http://shrivv.com/Technicle/QA_HP_Tutorial.pdf','HP Quality Center Tutorial',NULL),
 (48,10,'https://jazz.net/help-dev/clm/index.jsp?topic=%2Fcom.ibm.rational.test.qm.doc%2Ftopics%2Fc_testcase_overview.html','IBM Rational Software information Center',NULL),
 (49,3,'http://www.bredemeyer.com/pdf_files/functreq.pdf','"Functional Requirements and Use Cases", Ruth Malan and Dana Bredemeyer, Bredemeyer Consulting',NULL),
 (50,3,'http://www.bredemeyer.com/pdf_files/use_case.pdf','"A Use Case Template: draft for discussion", Derek Coleman, Hewlett-Packard Software Initiative',NULL),
 (51,3,'http://ieeexplore.ieee.org/ielx5/5445539/5445587/05445616.pdf?tp=&arnumber=5445616&isnumber=5445587','X. J. Zheng, X. Liu, & S. Liu. (2010). Use Case and Non-functional Scenario Template-Based Approach to Identify Aspects. Computer Engineering and Applications ICCEA 2010 Second International Conference on (Vol. 2, pp. 89-93)',NULL),
 (52,3,'http://publib.boulder.ibm.com/infocenter/rtnlhelp/v6r0m0/index.jsp?topic=%2Fcom.ibm.xtools.modeler.doc%2Ftopics%2Fcextend.html','Extend relationships',NULL),
 (53,1,'http://www.jiludwig.com/reiber/requirements_trace.html','Requirements Trace-ability and Use Cases',NULL),
 (54,3,'http://www.jiludwig.com/reiber/requirements_trace.html','Requirements Trace-ability and Use Cases',NULL),
 (55,3,'http://www.andrew.cmu.edu/course/90-754/umlucdfaq.html','UML Use Case Diagrams: Tips and FAQ',NULL),
 (56,2,'','',2),
 (57,2,'http://nptel.iitm.ac.in/courses/Webcourse-contents/IIT%20Kharagpur/Soft%20Engg/New_index1.html','Software Engineering, National Program on Technology Enhanced Learning',NULL),
 (58,2,'http://www.verifysoft.com/en_halstead_metrics.html','Halstead Metrics, Verifysoft Technology',NULL),
 (59,10,'http://www.doqs.com/pdf/DOQSTestPlanning.pdf','Developing Test Plans',NULL),
 (60,5,'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.94.1778&rep=rep1&type=pdf&ei=_5KtTqPLN8XMrQeZltG7DA&usg=AFQjCNFVBf-jL2ZUfyuldbJmjST1zFsrig&sig2=HRfe_1TUy4Q9UB66xduKtw&cad=rja','I. Y. Song, K. Yano, J. Trujillo, and S. Luján-Mora. "A Taxonomic Class Modeling Methodology for Object-Oriented Analysis", In Information Modeling Methods and Methodologies, Advanced Topics in Databases Series, Ed. (J Krostige, T. Halpin, K. Siau), Idea Group Publishing, 2004, pp. 216-240.',NULL),
 (61,7,'http://en.wikipedia.org/wiki/Class_diagram','Class diagram',NULL),
 (62,7,'http://www.objectmentor.com/resources/articles/umlClassDiagrams.pdf','UML Tutorial: Part 1 -- Class Diagrams',NULL),
 (64,9,'https://engineering.purdue.edu/~milind/ece573/2011spring/lecture-11.pdf','Control flow graphs and loop optimizations - Purdue Engineering',NULL),
 (65,9,'http://www.cs.wright.edu/~tkprasad/courses/cs781/L31CFA.pdf','Control Flow Analysis',NULL),
 (66,9,'http://www.cs.arizona.edu/~collberg/Teaching/453/2009/Handouts/Handout-15.pdf','Basic Blocks and Flow Graphs',NULL),
 (67,9,'','',9),
 (68,9,'http://lecturer.ukdw.ac.id/willysr/rpl2-ti/measuring_complexity.pdf','Measuring Structures (Complexity)',NULL),
 (69,9,'http://dl.acm.org/citation.cfm?id=807712','Thomas J. McCabe, "A Complexity Measure," in Proceedings of the 2nd International Conference on Software Engineering. IEEE Computer Society Press, Los Alamitos, CA, USA, 407-, 1976.',NULL),
 (70,9,'http://www.sei.cmu.edu/reports/97hb001.pdf','"C4 Software Technology Reference Guide", Software Engineering Institute (SEI)',NULL),
 (71,9,'http://onjava.com/onjava/2004/06/16/ccunittest.html','Cyclomatic Complexity',NULL),
 (72,9,'http://www.aivosto.com/project/help/pm-complexity.html','Complexity Metrics',NULL),
 (73,9,'http://dl.acm.org/citation.cfm?id=631131','S. R. Chidamber and C. F. Kemerer, "A Metrics Suite for Object Oriented Design," in IEEE Trans. Softw. Eng. 20, 6, 476-493. Jun 1994.',NULL),
 (74,9,'http://leepoint.net/notes-java/principles_and_practices/complexity/complexity-java-method.html','Java: Method Cyclomatic Complexity',NULL),
 (75,9,'http://www.jot.fm/issues/issue_2005_11/article1/','M. Genero, M Piattini, and C. Calero: “A Survey of Metrics for UML Class Diagrams,” in Journal of Object Technology, vol. 4, no. 9, November-December 2005, pp. 59-92.',NULL),
 (76,7,'','',3),
 (77,8,'','',2),
 (78,7,'http://www.docstoc.com/docs/33368785/The-UML','Synchronous messages The UML',NULL),
 (79,7,'http://www.tracemodeler.com/articles/a_quick_introduction_to_uml_sequence_diagrams/','Asynchronous message , UML sequence diagram',NULL),
 (80,7,'','',10),
 (81,8,'http://nptel.iitm.ac.in/courses/Webcourse-contents/IISc-BANG/System%20Analysis%20and%20Design/pdf/Lecture_Notes/LNm5.pdf','NPTEL course material - System Analysis and Design',NULL),
 (82,8,'http://virtual-labs.ac.in/cse08/isad/8/simulation/','Software Engineering Virtual Lab - Simulation',NULL),
 (83,8,'http://virtual-labs.ac.in/cse08/isad/8/case_study/','Software Engineering Virtual Lab - Case Study',NULL),
 (84,8,'','',3);
